testing using testify. Stage 1
muslite/go-testify pull request #1
Opened 2024-11-04 18:07 UTC by muslite

2024-11-04 21:37 UTC, dirtymew requested changes
Привет Евгений

по работе есть замечания - нужно поправить

2024-11-04 21:37 UTC, dirtymew commented on precode.go
> +    req := httptest.NewRequest("GET", "/cafe?count=5&city=moscow", nil)
тесты и код в go пишутся в разных файлах

те тесты должны быть в файле precode_test.go

2024-11-04 21:37 UTC, dirtymew commented on precode.go
> +    require.Lenf(t, bodyList, totalCount,
assert

2024-11-04 21:37 UTC, dirtymew commented on precode.go
> +    require.NotEmptyf(t, body, "expected not empty responce body")
похоже ты смешал 2 разных тест кейса в один
 

нужно вынести тест кейс в отдельный тест 
```
Запрос сформирован корректно, сервис возвращает код ответа 200 и тело ответа не пустое.
```

2024-11-04 21:37 UTC, dirtymew commented on precode.go
> +    require.Equalf(t, wrongCity, body, "expected server's message: '%s', got '%s'", wrongCity, body)
assert

2024-11-05 07:19 UTC, muslite commented
Разделил тесты и код сервера. 
Разделил на 2 тесты.  Каждый описан отдельно. 
...не уловлю пока на данном примере/задании грань между использованием require и assert
Попробовал "поиграться" в разных сочетаниях. Толи я что то не то делаю толи поведение одинаково. (go version go1.23.1 darwin/arm64) Что несколько удивительно. ( видимо что то у меня не так или делаю не так) 
 Потенциально  в тесте "TestMainHandlerServerRespondsCorrectly" проверка на код ответа может быть require , если не выполняется, то остальное проверять не имеет смысла. 
 
 Про слитые в один. 
Смутило что в уроке "Пакет testify" примеры шли в одном и в репозитории в одном "фале".  Как такое исполнять не понял, не нашел. Предположил что может так надо.  Прошу прощения.

2024-11-05 10:20 UTC, dirtymew approved these changes
Евгений

по заданию зачет

по вопросам дал комментарии

2024-11-05 10:20 UTC, dirtymew commented on precode_test.go
> +    assert.Equalf(t, http.StatusOK, status, "expected status code: %d, got %d", http.StatusOK, status)
require - в теории есть описания про то чем они отличаются

в кратце - если сработает require тест прекращает работу
если assert тест продолжит выполнения дальше

2024-11-05 10:20 UTC, dirtymew commented on precode_test.go
> +    assert.Equalf(t, http.StatusOK, status, "expected status code: %d, got %d", http.StatusOK, status)
require

2024-11-05 10:20 UTC, dirtymew commented on precode_test.go
> +    assert.Equalf(t, http.StatusBadRequest, status, "expected status code: %d, got %d", http.StatusBadRequest, status)
require

2024-11-05 17:45 UTC, muslite commented
Премного благодарен. 
Этот раз я полез в крайности.  Хоть и явно напрашивалось что соответствие статуса ответа обязательное требование.

2024-11-05 17:50 UTC, merged